[package]
name = "piston-demo4"
version = "0.1.0"
authors = ["Pavel Tisnovsky <ptisnovs@redhat.com>"]

[dependencies]
piston = "0.33.0"
piston2d-graphics = "0.21.1"
pistoncore-glutin_window = "0.39.0"
piston2d-opengl_graphics = "0.46.0"
piston_window = "0.70.0"
